### ISSUE TITLE
Record of Completed Purchases

### ISSUE THREAD

**Issue by FaisalBiyari** [disfordottie/insaneAppPurchaser#4]
More of a question than an issue.
With the list of 1.5 million apps, as the speed of licensing through ipatools, I estimate it would take a little under two months to complete the list.
Errors include:
• purchasing paid apps is not supported
• failed to purchase item with param 'STDQ': license already exists
• failed to purchase item with param 'STDQ': failed to purchase app

(For the Failed to Purchase app, I was trying to run the script in multiple instances to speed the process of purchasing, and that error started showing, for your record)

The question here becomes:
When there is a new list of 1.6 or 2 million apps, would there be a way for the script to recognize apps that have already been purchased and skip them, to streamline the process of purchasing apps? (vs. wasting months going through failed purchases due to "license already exists", which would probably trigger apple to block this some how)

**Comment by disfordottie** [comment]
First of all thanks so much for taking the time to write all that! 

"(For the Failed to Purchase app, I was trying to run the script in multiple instances to speed the process of purchasing, and that error started showing, for your record)" 

- Thanks for trying because I was actually going to try that myself, it sucks that it doesn't work.

I will keep trying to find ways to speed it up though, as the reason I made this script was to make sure whenever an app gets remove I can still download it, which requires having all apps, and I'm sure most people don't want to leave a computer running for 2 months. So unless I can find a way to speed it up, that list might just have to be for the really dedicated people 😂

 I want it to be fast but I also want to make sure it doesn't skip any apps.

"When there is a new list of 1.6 or 2 million apps"

- The app dump i sourced the bundle ids from wasn't made by me, and I have no idea how it was done in the first place, so unless they do it again I think this will be the final size.

For the skipping apps you already have idea, unfortunately the only way to check for those errors is to actually try and purchase it, I might be able to remove paid apps from the list though. If the list did get bigger though, I would make sure it didn't have any from the old list, to avoid those errors.

So far I haven't found and restrictions to purchasing lots of apps, because my apple id has 60k+ on it. I will however be making a test apple id and try to purchase all the apps on that with a computer running 24/7.

**Comment by FaisalBiyari** [comment]
My pleasure, and thank you for creating the script!

1. To add to the list of errors:
• "request failed: request failed: Get \"https://itunes.apple.com/lookup?bundleId=com.rmpos.ActionSystems&country=US&entity=software%2CiPadSoftware&limit=1&media=software\": failed to make round trip: dial tcp: lookup itunes.apple.com: no such host" success=false

This error occurred when my laptop disconnected from WiFi.

2. I believe the speed limitation is related to apple servers, limiting the requests/approvals, but that is just a guess.
I considered using multiple Apple IDs to break down the list, but that just complicates access to the apps.

Two months is an "initial investment" for the die hard enthusiasts of us, I would say, but the real challenge becomes identifying new apps added to the store and immediately purchasing it. The most critical apps are usually the ones that are removed in less than 24 hours of being added to the store.


But all of that is off topic.
For the point of keeping record, I was thinking that maybe the script can generate a list that contains the apps that succeeded, as well as the apps that failed, with the recorded error, and for long term success, keep record of the apple ID that was used for the purchases, so that when the apple ID is changed, the records are separated.

The reasoning would be:
• Apps that succeed would be entered into a "Do not purchase again" list, for speed optimization
• Apps that failed due to already owned license would also enter the "Do not purchase again" list, also for speed optimizations
• Apps that failed due to paid app would be in a permanent list for blocked/paid apps, for speed optimization
• Apps that failed due to other reasons would be in some kind of "Try again" list, to not lose access to any apps.

What do you think about that?

**Comment by disfordottie** [comment]
1. I'm not sure what could be causing it to be so slow, I doubt apple is purposely making it slow, but it is definitely a possibility.

2. I like your thinking but unfortunately I have no experience with API's and the like so someone else would have to help with that part, I can definitely make a log system. The script does already have a option to resume from where you left off, but that has room for improvement. 
 
- Lists would be useful and i'll get started on it. You've pretty much nailed it category wise, I can't think of any others you would need. 

Alternatively if I can't get some sort of api (or whatever you would call it) working (it seems like a big job and a server would be needed, alot have tried and failed in the past, most recently Tool Lancely) I could possibly release more lists (eg a part 2 list) and I'd make sure it doesn't have duplicate apps from list 1 (To save time purchasing duplicates for people who already purchased list 1), however that has the obvious downside of missing apps that get released and promptly deleted. 

But for now ill get started on a log system, thanks for all the suggestions!
